services:
  adminer:
    image: adminer
    ports:
      - ${ADMINER_PORTS}
    restart: always

  db:
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    image: postgres
    ports:
      - ${DB_PORTS}
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    restart: always
    ports:
      - ${REDIS_PORTS}
    volumes:
      - redis_data:/data

volumes:
  pgdata:

  redis_data:
