services:
  adminer:
    image: adminer
    ports:
      - 8081:8080
    restart: always

  db:
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    image: postgres
    ports:
      - 5431:5432
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    restart: always
    ports:
      - 6379:6378
    volumes:
      - redis_data:/data

volumes:
  pgdata:

  redis_data:
