services:
  adminer:
    image: adminer
    ports:
      - 8081:8080
    restart: always

  db:
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres
    ports:
      - 5431:5432
    restart: always
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
